import Image from 'next/image'
import { Inter } from 'next/font/google'
import Head from "next/head";
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Hello Twiter</h1>
    </div>
  );
}
